import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "vinext app",
  description: "Generated by create-vinext-app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ja">
      <body>
        <nav className="navbar is-link">
          <div className="navbar-brand">
            <span className="navbar-item">Trial Tmp App</span>
          </div>
        </nav>
        <div className="container pt-3">{children}</div>
      </body>
    </html>
  );
}
